export const cars = [
  {
    id: 1,
    name: "Prado",
    type: 'SUV',
    brand: "Toyota",
    description: "description test",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "",
    image3: "",
  },
  {
    id: 2,
    name: "Mercedes amg",
    type: 'Luxury car',
    brand: "Toyota",
    description: "description test",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "",
    image3: "",
  },
];
