export const cars = [
  {
    id: 1,
    name: "Prado",
    type: 'SUV',
    brand: "Toyota",
    description: "The Toyota prado has 1 Diesel Engine and 1 Petrol Engine on offer. The Diesel engine is 4461 cc while the Petrol engine is 3956 cc . It is available with Automatic transmission.Depending upon the variant and fuel type the prado has a mileage of 7.3 to 8.0 kmpl & Ground clearance of prado is 220 mm. The prado is a 8 seater 6 cylinder car and has length of 4,715 mm, width of 1,875 mm and a wheelbase of 2,790 mm.",
    descriptionEsp: "El Toyota Land Cruiser Prado cuenta con un fuerte carácter y un atractivo y robusto diseño basado en líneas agresivas y estilo compacto de gran elegancia con una mezcla de texturas de forma armónica para brindar un diseño que otorga distinción. Este potente todo terreno se ha reinventado y superado a sí mismo.",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "https://www.toyotarp.com/images/ImagenesModelo/Prado/lineup/GT5L-8.webp",
    image3: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image4: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image5: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image6: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
  },
  {
    id: 2,
    name: "Mercedes amg",
    type: 'Luxury car',
    brand: "Toyota",
    description: "description test",
    descriptionEsp: "description espanol",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image3: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
  },
];
