export const cars = [
  {
    id: 1,
    name: "Prado",
    type: 'SUV',
    brand: "Toyota",
    description: "El Toyota Land Cruiser Prado cuenta con un fuerte carácter y un atractivo y robusto diseño basado en líneas agresivas y estilo compacto de gran elegancia con una mezcla de texturas de forma armónica para brindar un diseño que otorga distinción. Este potente todo terreno se ha reinventado y superado a sí mismo.",
    descriptionEsp: "El Toyota Land Cruiser Prado cuenta con un fuerte carácter y un atractivo y robusto diseño basado en líneas agresivas y estilo compacto de gran elegancia con una mezcla de texturas de forma armónica para brindar un diseño que otorga distinción. Este potente todo terreno se ha reinventado y superado a sí mismo.",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "",
    image3: "",
  },
  {
    id: 2,
    name: "Mercedes amg",
    type: 'Luxury car',
    brand: "Toyota",
    description: "description test",
    descriptionEsp: "description espanol",
    model: 2019,
    price: 68.99,
    imageMain: "https://www.toyota.com.co/wp-content/uploads/2020/08/PLATA-METALICO-14.jpg",
    image2: "",
    image3: "",
  },
];
